#
# Configuration file for tracking using sliding
# 

dynamics:
    control_points: [
        [0.04, 0.0], [0.04, 0.08], [0.0, 0.08], [-0.04, 0.08], [-0.04, 0.0], [-0.04, -0.08], [0.0, -0.08], [0.04, -0.08], [0.04, 0.0]
    ] # [meter]
    x_len: 0.08
    y_len: 0.16
    pusherRadious: 0.007 #  [meter]
    pusherFricCoef: 0.1
    pusherForceLim:  0.3
    pusherAngleVelLim: 3.0
    Kz_max: 50.
    Kz_min: 50.
    xFacePsiLimit: 0.9
    # yFacePsiLimit: 0.405088
    yFacePsiLimit: 0.52

TO:
    contactMode: 'sliding_cc_slack'  # 'sticking', 'sliding_cc', or 'sliding_mi'
    # contactMode: 'sliding_cc_slack'  # 'sticking', 'sliding_cc', 'sliding_cc_slack', or 'sliding_mi'
    # contactMode: 'sliding_mi'  # 'sticking', 'sliding_cc', 'sliding_cc_slack', or 'sliding_mi'
    # contactMode: 'sliding_cc_slack'  # 'sticking', 'sliding_cc', 'sliding_cc_slack', or 'sliding_mi'
    contactFace: '-x'  # '+x', '-x', '+y', '-y'
    solverName: 'ipopt'  # 'ipopt', 'snopt', 'gurobi', 'qpoases', 'knitro'
    # solverName: 'knitro'  # 'ipopt', 'snopt', 'gurobi', 'qpoases', 'knitro'
    W_x: [1.0, 1.0, 0.01, 0.001]  # diagonal state weights
    W_u: [0., 0., 0., 0.]  # diagonal control weights
    K_goal: 1
    X_goal: [0.4, 0.2, 0.3, 0.]
    numObs: 0
    # X_goal: null
    linDynFlag: False
    codeGenFlag: False
    noPrintingFlag: False
    phases: null
